In [1]:
import numpy as np

In [5]:
x1 = np.arange(1,11)
x2 = np.arange(1,11).reshape(10,1)
x3 = np.arange(1,11).reshape(1,10)

In [8]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(10,)
(10, 1)
(1, 10)


In [14]:
print(x1)
print(x2)
print(x3)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [16]:
print(x1[2])
print(x2[2,0])
print(x3[0,2])


3
3
3


In [20]:
shape1 = x1.shape
shape2 = x2.shape
shape3 = x3.shape
print(shape1)
print(shape2)
print(shape3)
print(len(shape1))
print(len(shape2))
print(len(shape3))


(10,)
(10, 1)
(1, 10)
1
2
2


In [14]:
array = np.arange(10)
vector = np.arange(10).reshape(10,1)

In [22]:
array.shape

(10,)

In [21]:
vector.shape

(10, 1)

In [24]:
np.version.version

'1.16.5'

In [25]:
!pip install numpy?

Object `numpy` not found.


In [27]:
!pip install --upgrade numpy

  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:
      Successfully uninstalled numpy-1.16.5


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\users\\saurmisr\\appdata\\local\\continuum\\anaconda3\\lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp37-win_amd64.pyd'
Consider using the `--user` option or check the permissions.



In [28]:
np.version.version

'1.16.5'

In [29]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])